### ISSUE TITLE
Register by email authentication code 

### ISSUE THREAD

**Issue by Qingyang0818** [JoyfulTechLauncher/joyfulfashionista_app_beta#49]
Trying to send authentication code to user by the email they entered, in this way, we can verify user's email address

**Comment by Qingyang0818** [comment]
Now, user can enter their email address in the app and our system will send a email with random authentication code to user. User need to use that code to finish the registry process.
This is use our gmail id and passowrd to log in the gmail to send email to users, we may try to use a more safe way such as oauth2 to finish it.

**Comment by Anjun-Feng** [comment]
Reopened as not merged yet

**Comment by Anjun-Feng** [comment]
Close as now resolved and merged

**Comment by Anjun-Feng** [comment]
Close as now resolved and merged
