### ISSUE TITLE
Check if the username and email are already in use in Register page

### ISSUE THREAD

**Issue by JunyiLi0804** [JoyfulTechLauncher/joyfulfashionista_app_beta#62]

**Comment by Qingyang0818** [comment]
Fix this issue by checking the error information given by wordpress to determine which error it is and show it to the user.
Now user can know which error they have made by the error message.
![屏幕截图 2023-09-27 004343](https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/67152451/fe
![屏幕截图 2023-09-27 004444](https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/67152451/ede267ae-5de9-4049-8613-c57039af5206)
56204e-bf6e-478a-903d-efce4f0f3bd5)
