### ISSUE TITLE
Categories cannot be retrieved on the home page

### ISSUE THREAD

**Issue by Anjun-Feng** [JoyfulTechLauncher/joyfulfashionista_app_beta#74]
Connect the categories on the home page to the server.
![image](https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/110949485/09fe7ab2-6502-4f4d-b12c-bc033e5419cc)

**Comment by Anjun-Feng** [comment]
Now temporarily fixed. See f5cfb20

**Comment by wenshilanR** [comment]
Now fixed in [56d24be](https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/commit/56d24be42845a3437a025a1c65ea2d35ac8f0830)

**Comment by Anjun-Feng** [comment]
Close as issue resolved
