### ISSUE TITLE
Duplicated products are displayed on the home page

### ISSUE THREAD

**Issue by wenshilanR** [JoyfulTechLauncher/joyfulfashionista_app_beta#84]
On the home page, after scrolling down to the bottom and releasing to reload, duplicated items will be displayed.

<img width="264" alt="截屏2023-08-27 20 42 43" src="https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/90823176/ce7bcaef-4471-4129-bc5b-165541828e6b">/

<img width="266" alt="截屏2023-08-27 20 43 05" src="https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/90823176/5bde2a2a-7b7b-4a53-9f74-58b95eb318ca">

**Comment by Anjun-Feng** [comment]
Close as issue resolved

**Comment by Anjun-Feng** [comment]
Close #88
