### ISSUE TITLE
Products are not classified according to categories

### ISSUE THREAD

**Issue by wenshilanR** [JoyfulTechLauncher/joyfulfashionista_app_beta#85]
On the category page, products are not classified, and duplicated products are displayed

<img width="268" alt="截屏2023-08-27 20 43 48" src="https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/90823176/dde44dcb-bf9e-45ff-941c-91b00a53b615">

<img width="267" alt="截屏2023-08-27 20 43 29" src="https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/90823176/2abbaf47-66ab-4e31-aaa4-a1c26ef15936">

**Comment by Anjun-Feng** [comment]
Close as completed
