### ISSUE TITLE
Product details cannot be displayed correctly

### ISSUE THREAD

**Issue by wenshilanR** [JoyfulTechLauncher/joyfulfashionista_app_beta#86]
After clicking on a product and navigating to the product detail page, the product details are not correct.

<img width="266" alt="截屏2023-08-27 20 44 26" src="https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/90823176/3e77547f-f98e-46fb-8588-aab54a9fe230">

**Comment by Qingyang0818** [comment]
Using method to get the color and size attributes in products. Now, app can show the correct color and size.
![屏幕截图 2023-08-29 042200](https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/67152451/b5367270-e5d8-40d9-a207-030e98654fec)

PS:
Before, the developer are tring to use data get from (http get) data in products/attributes/1/terms
That id is confused so i change another way.
Now, Related data location: product/attributes/id=1 for color,2 for size/options 
But this location could directly get by http get, we have to find it in product data.
