### ISSUE TITLE
Profile page layers overlap

### ISSUE THREAD

**Issue by Anjun-Feng** [JoyfulTechLauncher/joyfulfashionista_app_beta#97]
**Describe the bug**
Profile page widgets overlap. Sometimes the upper one overlaps the lower one, sometimes behaves in an opposite way

**To Reproduce**
1. Go to 'Profile'
2. Click on 'casually swipe the screen until layers overlap'

**Expected behavior**
No widgets  should overlap

**Screenshots**
![ee0a876663f02b855bc89591035848b](https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/110949485/0520b147-8afa-4d73-bd49-a5f5b7539783)

**Comment by JaniceSi** [comment]
It appears normal on my side of the ios simulator, without overlap.

**Comment by JinyuChu09** [comment]
Issue resolved.
